run-name: CI Pipeline for pull request
name: CI

on:
  pull_request:
    branches:
      - main  

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Get PR Version
        id: pr_version
        run: |
          PR_VERSION=$(cat VERSION)
          echo "PR version: $PR_VERSION"
          echo "PR_VERSION=$PR_VERSION" >> $GITHUB_ENV

      - name: Get Main Branch Version
        id: main_version
        run: |
          git fetch origin main
          MAIN_VERSION=$(git show origin/main:VERSION)
          echo "Main version: $MAIN_VERSION"
          echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_ENV

      - name: Compare Versions
        run: |
          echo "Comparing PR version ($PR_VERSION) with main version ($MAIN_VERSION)..."

          PR_VER="${PR_VERSION#v}"
          MAIN_VER="${MAIN_VERSION#v}"

          if [ "$(printf '%s\n' "$MAIN_VER" "$PR_VER" | sort -V | head -n1)" = "$PR_VER" ]; then
            echo "ERROR: Version was not increased in VERSION file."
            exit 1
          fi

          echo "Version increased. Check Passed!"